version: '3.8'

services:
  worker:
    extends:
      file: docker-compose.yml
      service: worker
    environment:
      - HASHCAT_DEVICE_TYPE=amd
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    volumes:
      - ./volumes:/data
      - /opt/rocm:/opt/rocm:ro
