services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    environment:
      - HASHCAT_DEVICE_TYPE=amd
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    volumes:
      - ./volumes:/data
      - /opt/rocm:/opt/rocm:ro
    # Force IPv4
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
