services:
  # PostgreSQL Database for Testing
  postgres-test:
    image: postgres:15-alpine
    container_name: autopwn-postgres-test
    restart: "no"  # Don't auto-restart for ephemeral test environment
    environment:
      POSTGRES_DB: autopwn_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"  # Using different port (5433) for test DB
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d autopwn_test"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - autopwn-test-network
    tmpfs:
      - /tmp
      - /var/run/postgresql

  # Redis for BullMQ (Testing)
  redis-test:
    image: redis:7-alpine
    container_name: autopwn-redis-test
    restart: "no"  # Don't auto-restart for ephemeral test environment
    ports:
      - "6380:6379"  # Using different port (6380) for test Redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - autopwn-test-network

  # Redis Commander for Test Redis (optional, for debugging)
  redis-commander-test:
    image: rediscommander/redis-commander:latest
    container_name: autopwn-redis-commander-test
    restart: "no"
    environment:
      REDIS_HOSTS: local:redis-test:6379
    ports:
      - "8082:8081"
    depends_on:
      redis-test:
        condition: service_healthy
    networks:
      - autopwn-test-network
    profiles:
      - tools

volumes:
  postgres_test_data:
    name: autopwn_postgres_test_data
    driver: local
  redis_test_data:
    name: autopwn_redis_test_data
    driver: local

networks:
  autopwn-test-network:
    name: autopwn-test-network
    driver: bridge