services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    environment:
      - HASHCAT_DEVICE_TYPE=nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Force IPv4
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
