services:
  postgres:
    image: postgres:15-alpine
    container_name: autopwn-postgres
    environment:
      - POSTGRES_DB=autopwn
      - POSTGRES_USER=autopwn
      - POSTGRES_PASSWORD=change-this-password-in-production
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U autopwn']
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    image: ${DOCKER_IMAGE:-doomedramen/autopwn:latest-cpu}
    container_name: autopwn-app
    environment:
      - DATABASE_URL=postgresql://autopwn:change-this-password-in-production@postgres:5432/autopwn
      - BETTER_AUTH_SECRET=change-this-in-production-use-a-secure-secret
      - NODE_ENV=production
      - LOG_LEVEL=INFO
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./uploads_data:/app/uploads
      - ./jobs_data:/app/jobs
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/auth/status']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
