version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: autopwn-dev-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=autopwn_dev
      - POSTGRES_USER=autopwn
      - POSTGRES_PASSWORD=dev_password
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U autopwn -d autopwn_dev']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: autopwn-dev-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - dev_redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Database admin interface
  pgadmin:
    image: dpage/pgadmin4
    container_name: autopwn-dev-pgadmin
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@autopwn.local
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - dev_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  # Optional: Redis admin interface
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: autopwn-dev-redis-ui
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis

volumes:
  dev_postgres_data:
  dev_redis_data:
  dev_pgadmin_data:
