import { test as base, expect } from '@playwright/test';

// Simply export the base test with expect
export const test = base;
export { expect };

// Helper function to access credentials
export const getAdminCredentials = () => ({
  email: process.env.E2E_ADMIN_EMAIL || 'admin@autopwn.local',
  password: process.env.E2E_ADMIN_PASSWORD || 'autopwn-test-password' // This should match the password generated by API in test mode
});