name: Build, Test and Deploy to DockerHub

on:
  push:
    branches: [main, master]
    tags: ['v*.*.*']
  pull_request:
    branches: [main, master]

# Set workflow permissions for security and functionality
permissions:
  contents: read
  packages: write
  pull-requests: write
  security-events: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: autopwn
  NODE_VERSION: '20'

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    outputs:
      build-success: ${{ steps.build.outcome }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install lefthook
        run: pnpm add -g lefthook

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type check
        id: typecheck
        run: pnpm tsc --noEmit

      - name: Run linting
        id: lint
        run: pnpm lint:fix

      - name: Check formatting
        id: format
        run: pnpm format:check

      - name: Run build
        id: build
        run: pnpm build
        env:
          NODE_ENV: production
          DATABASE_URL: 'postgresql://test:test@localhost:5432/test?connect_timeout=10&statement_timeout=10'
          NEXT_PUBLIC_APP_URL: http://localhost:3000
          BETTER_AUTH_SECRET: github-action-build-secret-32-chars-long
          BETTER_AUTH_URL: http://localhost:3000

  test:
    name: Run All Tests
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.build-success == 'success'

    outputs:
      tests-success: ${{ steps.tests.outcome }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install lefthook
        run: pnpm add -g lefthook

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        id: unit-tests
        run: pnpm test:run || pnpm test
        continue-on-error: false

      - name: Run integration tests
        id: integration-tests
        run: pnpm test:integration
        continue-on-error: false

      # E2E tests skipped in CI - run locally for comprehensive testing
      # Use: pnpm test:e2e for local E2E testing

      - name: Run security audit
        id: security-audit
        run: pnpm audit --audit-level moderate || echo "⚠️ Security audit completed with issues"

      - name: Mark tests as successful
        id: tests
        run: echo "All tests completed successfully"

  deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest
    needs: [build, test]
    if: |
      github.event_name == 'push' &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) &&
      needs.build.outputs.build-success == 'success' &&
      needs.test.outputs.tests-success == 'success'

    outputs:
      image-tag: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production
            NEXT_PUBLIC_APP_URL=http://localhost:3000
            BETTER_AUTH_SECRET=github-action-build-secret-32-chars-long
            BETTER_AUTH_URL=http://localhost:3000
            DATABASE_URL=postgresql://test:test@localhost:5432/test

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ steps.meta.outputs.version }}
          path: sbom.spdx.json
          retention-days: 30

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: deploy
    if: |
      github.event_name == 'push' &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) &&
      needs.deploy.result == 'success'

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.deploy.outputs.image-tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
